apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-k
    camel.apache.org/component: operator
  name: camel-k-operator-v1
  namespace: default
spec:
  selector:
    matchLabels:
      name: camel-k-operator-v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: camel-k
        camel.apache.org/component: operator
        name: camel-k-operator-v1
    spec:
      containers:
      - args:
        - --monitoring-port=8080
        - --health-port=8081
        - --leader-election=false
        command:
        - kamel
        - operator
        env:
        - name: WATCH_NAMESPACE
        - name: OPERATOR_NAME
          value: camel-k
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KAMEL_INSTALL_DEFAULT_KAMELETS
          value: "false"
        - name: KAMEL_OPERATOR_ID
          value: v1
        image: docker.io/apache/camel-k:1.7.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: camel-k-operator
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
      serviceAccount: camel-k-operator
      serviceAccountName: camel-k-operator
      terminationGracePeriodSeconds: 30
